use clap::{App, Arg, ArgMatches};

pub fn get_matches() -> ArgMatches {
    let secret = Arg::new("secret")
        .about("Sets secret")
        .value_name("password")
        .takes_value(true)
        .required(true)
        .long("secret")
        .short('s');
    let provider = Arg::new("provider")
        .about("Sets provider")
        .value_name("provider")
        .required(true);
    App::new("Passman")
        .version("0.1.0")
        .about("Personal password manager")
        .subcommand(App::new("new")
            .about("Creates new password file")
            .arg(Arg::new("secret")
                .about("Sets secret")
                .value_name("password")
                .required(true)
            )
        )
        .subcommand(App::new("set")
            .about("Sets a new password")
            .arg(&secret)
            .arg(&provider)
            .arg(Arg::new("value")
                .about("Sets value")
                .value_name("value")
                .required(true)
            )
        )
        .subcommand(App::new("get")
            .about("Gets a password")
            .arg(&secret)
            .arg(&provider)
        )
        .subcommand(App::new("gen")
            .about("Generates a password")
            .arg(&secret)
            .arg(&provider)
        )
        .get_matches()
}
